modLoader="javafml"
loaderVersion="[38,]"
issueTrackerURL="https://github.com/Darkhax-Minecraft/Friendly-Fire/issues"
license="LGPL v2.1"

[[mods]]
modId="friendlyfire"
updateJSONURL="https://updates.blamejared.com/get?n=friendlyfire&gv=1.18"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
authors="${mod_authors}"
description='''
${mod_description}
'''