modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Darkhax-Minecraft/Friendly-Fire/issues"
license="LGPL v2.1"

[[mods]]
modId="friendlyfire"
updateJSONURL="https://updates.blamejared.com/get?n=friendlyfire&gv=1.15.2"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.friendlyfire]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.friendlyfire]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="SERVER"